name: 部署魔法森林大冒險網頁

on:
  push:
    branches: [ main ] # 當程式碼推送到 main 分支時觸發

jobs:
  deploy: # 這個任務名稱
    runs-on: ubuntu-latest # 在 Ubuntu 虛擬機上執行

    steps:
      - name: 檢查程式碼
        uses: actions/checkout@v4

      - name: 設定 Node.js (用於未來可能的網頁打包工具)
        uses: actions/setup-node@v4
        with:
          node-version: 20 # 使用 Node.js 20 版本

      - name: (模擬) 建置網頁檔案 (如果未來有複雜的網頁框架，這裡會執行建置指令)
        run: |
          echo "模擬網頁檔案建置中..."
          # 對於簡單的 index.html，實際上不需要複雜的建置步驟
          # 但如果未來使用 React, Vue, Angular 等框架，這裡會是 npm run build
          echo "建置完成，準備部署！"

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # 使用一個專門用於部署到 GitHub Pages 的 Action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub 提供的自動驗證 token
          publish_dir: ./ # 告訴 Action 要部署哪個資料夾的內容，這裡指專案根目錄
          # CNAME: your-custom-domain.com # 如果你有自己的網域，可以取消註解這一行並填入